const { exec } = require('child_process');
const fs = require('fs');

console.log('Running tests for Memory Game...');

exec('npm test', (error, stdout, stderr) => {
  if (error) {
    console.error(`Error executing tests: ${error}`);
    return;
  }

  // Read the output file generated by the test command
  fs.readFile('output.txt', 'utf8', (err, data) => {
    if (err) {
      console.error(`Error reading output file: ${err}`);
      return;
    }

    console.log('Test Results:');
    console.log(data);

    // Check if tests passed
    if (data.includes('Test Suites: 1 passed')) {
      console.log('\n✅ All tests passed successfully!');
    } else {
      console.log('\n❌ Some tests failed. Please check the output above.');
    }
  });
});